language: php
php:
- 5.3
source_key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQ0KUHJvYy1UeXBlOiA0LEVOQ1JZUFRFRA0KREVLLUluZm86IEFFUy0xMjgtQ0JDLDE1NEM3NDU1NzUyQTNDRTk5MjkyREUyMjJEN0FEQTgxDQoNCkpzN1FLeHRmdENWbiswUEJlVzgvYm8xZ2RJZkNBby9jRStGbjMrZ2JudFd1dkpUdXJ1QlVrU0ZhNnRrR1IxbDUNCkRuM1pYcHY0dGwxMjAyaXNGMzFBNEtuV3RqQ3pacmV4ZlhuaGc3d3dvaFN2TGFVOW1BSFZhWjBiZXBHRm5sV1ANCnZ6MkJuaXdyMUJITEx1cjlGbnJjaFVzWnVaN0l0Z3pXNzg5MDIyVUI0NE9jK0FqMjZTbHFZb2Z5Z2dTaW1YQlcNCnFBZDVmZkxFUkhNemtUOGhXUHAxc0REeHp2NExoNXVIQ3FVSnM3MHQ0blZuMURlQ0xMbmx2RUhlU1c0T2hNM1QNClVyZTN5bE50b0k0RytUNWFPa3J4VFROd0RpQVRwVExiYmRHMFVrK0E5VzV1MTRKMDlGdS9TRXNoWmdvRGVoRUoNCll2ZHN0Wk5TalBQY1BrK2IybURNR29wQklHcmNMelhjRnlFODhoa2U0Y05aWlB5STNadTc3MVpiWHNyNzkwbTENCmw2K3JuNnJwOGJONzV2S0pMRDRqMEMzUkJVOXhBMlFQZmdLWnl6cUI5MHlnUStIVUV5RnRnTDVMUFZGM1h3NzgNCks1TnljRU8renFEZ09xVjdyalluaDkwVms0bUJONTJ6Y1JFQllDbUcyalBLQ0pCbHV4cU9MZVBRUzM1cUR2SWMNCkw5S2dkak5IUnd4RnlIaXZTbHU2Q3duckZ1R25zcnZoQ05IekdyNTlXenRRdEFiK25GZG9GSDVtQ0Rpa3JkeDMNCmJjaEJ5M2NmVUpEQmFDSUdzNUdXQmZpUmtsRFBwOE9paTVhcUlHLzhSOFQvakhtUytxeVJlRGRYdllLQ0N0VDINCkFzVHZOSWU0QmV3bHBNYUFhcVg3cEVQSjNEOFdzTVZLRU10UDVhTUI4T2s1SThZMnoySDJCN1hwZTlkbWFtc0ENCnJ2K2M5Y2lKSm91VDNPVTUxUjRic2tLbzVHNHZzRGpQczNWWGRyNFZib2g3ZlRqSEtvUjZqRjhxTXNvNUNZQ24NClkvRGFmeko2TVV3cGRxQUtiZUpZS0syS2JMN2IySFYrMFRoQ09HcHMzYW8wNE1OVWtlL3RVUkRGZGg4bWRwcmQNCms3VjB5ZmlwYkN3b3FnWDE4VVZKTXludTFDQjFNbDlwdU8xaEd5Z3pDWnNHbFdmd2ZWeXdnMzYvRkZLQVpMeTkNCmJXWXBrRXhoa29QY3FMV0JJNXhtMnFCb2R5OWNCTko3Uk9WaUJ1NHc3TldrcytxajZIemhmZUVFaW9BakNoYTMNCjVRNmJNVW5SQTNZeEV6dUNlWTdEQkV4Nnc3WWRNOGdjOVhVZ1UySFNibVk1WWpwOHh0OEM1K3hKaEQreEFsYk0NCmdMQVBJYUdYNVJVQjlqVVZyYmdXbCs2VXY3bmZCUGpFRU1iMU0yaEdCQ3FpcDRtbTB6djYyMWIxQUdyN3pOenYNCk9HYTRwTXFuT1o0NWtoVktxc0FzT2NzMkhZdmFDcHkzMjdJWWQySjd4R0JuN1Q3QWMvQnV5Tm9wZzdZUUZTUFYNClBLZGpJOGIrYjdQT1gxZGhmSWpNZWc1NUd1YWoyaitPeDN1ajlvZ0FWRXhQZVZiZWs4T1ZuSS9KSEdrQ0drL1QNCi9iWjFFMmtRQzNGa2V3Mmxob2ZaTGR3Qk1uVWd3ZzdrR2VNNmU0NFVodEkyK1MxTXJ3MmVwa1Q3bkQwenN5SWUNCmVsengyN1VLMzd2UExmUkFFV0M3RkZkYlVUYjAxVWdxZE5vaXdGUXVYdWpNVDNwd1cyd015a0xaMnZCQ0cxTE8NCmdFemFIL1ExdFRaZFlUZGhKWmJueHI2UWdBZXg3Qm1hZWhDQms2aUsrZlhSTVBYa0N6aDB5U1BOWmsyS2xjTHkNCncrWHNuTVNiVXNuV2NRODlVeVhmd0NlbjNGZy94aE1tcXllY1BleHkxejJOcXpJWmZRN1Ricm5qMi9nM1U0c1oNCk53Vlk4bmcwbUxCWUJiUGZSY0dtbVF3MG9BTlkrTlVIbVNJYnhyWjhZMmNSNHZrN3F0dVFnWjlZVWRNc0VIUVgNCjIwOWFyUWtaMTAwWm9Od3o4K0x3Vm1lQW9raDRvSzVOMlRIZml2MHNnVTU2d3lDalo4cGVHUU9xWnFJbFRqVncNCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0t

env:
  global:
  - PUUID='ed64345a-aa95-4e9e-b919-1fe9e8537ce6'
  - PNAME='10stepstest'
  - PSOURCE='dev'
  - secure: E4Xtuee9bZ9iqFKPyTR3hA5dE/su7iz9sW1Qb2B6Al+Wh9EDoC9IJlF/g6MypVvduAKeSoIf9Judnnr1xt/E324OxYKCRFBAWpfFn8pnNchO2kFacwCX54q2ZnHxdg1Mhpcw1dUo61+7FvrKK6q9sg4LVZ+CzxuPi6p/3Ly/Fgc=
  - secure: U+wHmgqjuk14i0OLMPd+fH2XJ0o1F4PmAtDwT4ylVd8Onz3E4IFCI35W8EqgrUaAT83vNz8hm/+N83y8ktusXIHX2Zl5ow8J5/XG/Ireokc7sfgPSsnpHOZ+N6/gbjed80/RSMZQ596dy2bE6eZsrdFFJd/LRTYaJ4zpAmhJkVw=
  - PSITE=$(cat /dev/urandom | tr -cd 'a-z0-9' | head -c 4)
  - PSITE="ci$TRAVIS_BUILD_NUMBER-$PSITE"
  - PHOST="https://$PSITE-$PNAME.gotpantheon.com"
install:
- bash scripts/install.sh
before_script:
#- bash scripts/before_script.sh
script:
#- bash scripts/run_tests.sh
after_script:
#- bash scripts/after_script.sh
notifications:
  email:
    recipients: 
    on_success: always
    on_failure: always
