language: php
php:
- 5.3
env:
  global:
  - PUUID='ed64345a-aa95-4e9e-b919-1fe9e8537ce6'
  - PNAME='10stepstest'
  - PSOURCE='dev'
  - secure: E4Xtuee9bZ9iqFKPyTR3hA5dE/su7iz9sW1Qb2B6Al+Wh9EDoC9IJlF/g6MypVvduAKeSoIf9Judnnr1xt/E324OxYKCRFBAWpfFn8pnNchO2kFacwCX54q2ZnHxdg1Mhpcw1dUo61+7FvrKK6q9sg4LVZ+CzxuPi6p/3Ly/Fgc=
  - secure: B36n51LDAYS/aPukaz9nnQAiOQLKb95aLNYqBrY7HGGSHnUgDa7098ZNCTqp/M0SDSeFLblfU44gi2hMpw8gfKPzhVvfn5iJocT5laXkWIB9MUJhTngCbponu1zC0UJqAgiIxfVpOSLrESHNJxbJxIzkSqDudijT8syLuEgPEeg=
  - PSITE=$(cat /dev/urandom | tr -cd 'a-z0-9' | head -c 4)
  - PSITE="ci$TRAVIS_BUILD_NUMBER-$PSITE"
  - PHOST="https://$PSITE-$PNAME.gotpantheon.com"
before_install:
- openssl aes-256-cbc -K $encrypted_5aa7ab7b39b5_key -iv $encrypted_5aa7ab7b39b5_iv
  -in training_rsa.txt.enc -out training_rsa.txt -d
install:
- echo "StrictHostKeyChecking no" > ~/.ssh/config
- composer global require drush/drush:6.2.0
- export PATH="$HOME/.composer/vendor/bin:$PATH"
- git clone https://github.com/pantheon-systems/terminus.git $HOME/.drush/terminus
- cd $HOME/.drush/terminus
- composer update --no-dev
- drush cc drush
before_script:
- drush pauth $PEMAIL --password=$PPASS
- cd $TRAVIS_BUILD_DIR
- git checkout -b $PSITE
- drush make drupal-org.make -y
- git remote add pantheon ssh://codeserver.dev.$PUUID@codeserver.dev.$PUUID.drush.in:2222/~/repository.git
- git config --global user.email "training@getpantheon.com"
- git config --global user.name "Pantheon Training"
- git add /$TRAVIS_BUILD_DIR
- git commit -m "Initial build"
- git push --force pantheon $PSITE
- drush psite-ecreate $PUUID $PSITE --source=$PSOURCE || true
- drush paliases
- drush cc drush
- cd $HOME
- drush @pantheon.$PNAME.$PSITE cc all --strict=0 || true
- drush @pantheon.$PNAME.$PSITE updb -y --strict=0
- drush @pantheon.$PNAME.$PSITE en simpletest -y --strict=0
- drush @pantheon.$PNAME.$PSITE vset -y simpletest_verbose 0 --strict=0
script:
- drush @pantheon.$PNAME.$PSITE test-run MyTestClass --strict=0
- drush @pantheon.$PNAME.$PSITE test-run MyTestClass2 --strict=0
after_script:
- drush psite-edelete $PUUID $PSITE -y
- cd $TRAVIS_BUILD_DIR; git push pantheon :$PSITE
notifications:
  email:
    recipients:
    on_success: always
    on_failure: always
