language: php

php:
  - 5.3


env:
  global:
    # Your Pantheon site's UUID (e.g. from your dashboard URL)
    - PUUID='7b67ea8d-0c67-41ec-9358-147b74181022'

    # Your Pantheon site's name.
    - PNAME='drush-make-example'

    # The Pantheon environment name from which Multidev DB/files will be pulled.
    # Probably one of: dev, test, live.
    - PENV='dev'

    # A random password for the drupal site install.
    - RANDPASS=$(cat /dev/urandom | env LC_CTYPE=C tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1 )

    # PEMAIL environment variable: represents the Pantheon account e-mail with
    # access to this site. Used to authenticate to Pantheon via Terminus. You
    # must cd to your project root and run:
    #
    # travis encrypt PEMAIL='test@example.com' --add env.global
    #
    # Which will eventually look something like the key below.
    # See: http://docs.travis-ci.com/user/build-configuration/#Secure-environment-variables
    #
    - secure: "IyugEqFFk0tqw1zQZTaYsTt88rq2EwQ+lz4S6DyXwRSLiAyWqxPfPF1J6lkzIOIaYoRCdXi3QBaHObJFQn0BQpJMMXvFZkwZ9mSTfAZbF2dnnVkO0gubGZr4jhVOpDnTS9JFNpmCCbkYzmxlRWJPQ6KhYUBGEiHo2aj5n8aXjWg="

    #
    # PPASS environment variable: represents the Pantheon account password for
    # the above encrypted e-mail address. Run:
    #
    # travis encrypt PPASS='my_account_password' --add env.global
    #
    - secure: "IKWSynH5dt6UqUDPd72RYXVy74k8DI6XvQ7MZyvKu3wUFne9VdyRwPvZr8FsxfN3aVOu1uvenQIEQh4eTCgccmbSUZZp5TWFR3B+Vq8JenXSI8BSbALMREd9ezZoondryJefbRpiGpbx5RK6oPDG8RtDEVqdUCUaBGaBglFIUzU="


    # Generate a random branch / multidev name, prefixed with "ci" followed
    # by the Travis build number. Note, due to Pantheon multidev environment
    # name limits, builds will start failing at #100000.
    - PSITE=$(cat /dev/urandom | tr -cd 'a-z0-9' | head -c 4)
    - PSITE="ci$TRAVIS_BUILD_NUMBER-$PSITE"

    # You can use $PHOST as a reference to the resulting multidev hostname.
    - PHOST="https://$PSITE-$PNAME.gotpantheon.com"

before_install:
    # Place a passphrase-free ssh key so that you can clone and push to your
    # Pantheon git repository.
    #
    # Use the travis encrypt-file command to generate your own.
    - openssl aes-256-cbc -K $encrypted_dfede703c127_key -iv $encrypted_dfede703c127_iv -in travis_rsa.enc -out ~/.ssh/id_rsa -d
    - chmod 0600 ~/.ssh/id_rsa

install:
  # Make some variables available to the travis-ci.sh script.
    - bash scripts/install.sh

before_script:
  # - $HOME/travis-ci.sh before-tests
  # - bash scripts/before_script.sh

script:
    - bash scripts/run_tests.sh

after_script:
  # - $HOME/travis-ci.sh after-tests
  # - bash scripts/after_script.sh

after_success:
  # Maybe promote to test here?

after_failure:
  # Maybe roll back?

notifications:
  email:
    recipients:
      # - panopoly-ci@googlegroups.com
    on_success: always
    on_failure: always
